/* NatureSea food — Orca hero: boat approach → docking → six boxes unloaded → delivered → next section.
 * One master timeline (ORCA_MASTER_PROMPT §4): scroll progress p (0…1) → master time → video frame + derived
 * box states. PC wheel/trackpad and phone vertical swipe are the same native scroll, so they drive the same p.
 * Nothing here blocks wheel/touch; pinch zoom stays available (no touch-action override).
 * Completion (§6): next section is "normal" only when deliveredCount===6 && remainingOnBoat===0 &&
 * lastBoxReleased && finalFramePresented. Failure/reduced motion → branded delivered poster, mode "degraded". */
(() => {
  'use strict';
  const T = window.ORCA_TIMELINE;           // generated by build_orca.py → orca/orca-timeline.js
  const root = document.getElementById('orca-hero');
  if (!T || !root) return;
  const stage = root.querySelector('.oh-stage');
  const video = root.querySelector('.oh-video');
  const finalImg = root.querySelector('.oh-final');
  const status = root.querySelector('.oh-status');
  // idle layer (2026-09-27 v3): before scrolling, a seamless loop of the boat floating on breaking waves plays on top
  // of the scrub video. It only fades out over the INTRO band — the scroll-driven master below is untouched.
  const idle = root.querySelector('.oh-idle');
  const reduce = matchMedia('(prefers-reduced-motion: reduce)');
  const phone = matchMedia('(max-width: 768px) and (orientation: portrait)');

  // ---------- timeline (single source of truth) ----------
  // States by master-reference seconds (36 s plan); p = sec / 36. Media time is mapped per state band.
  // [{state, p0, p1, m0, m1}] m = media seconds. p bands are identical on PC and phone; media seconds are per platform.
  let mediaKey = '';
  const M = () => (T.media[mediaKey] && T.media[mediaKey].bands) ? T.media[mediaKey] : T;
  const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
  function bandAt(p) { const B = M().bands; return B.find(b => p >= b.p0 && p < b.p1) || B[B.length - 1]; }
  function mediaTimeAt(p) {
    const b = bandAt(p), k = b.p1 > b.p0 ? clamp((p - b.p0) / (b.p1 - b.p0), 0, 1) : 1;
    return b.m0 + (b.m1 - b.m0) * k;
  }
  // box_i: onBoat → inHands → onDock, derived from media time (never from event counting)
  function boxesAt(m) {
    return M().boxes.map(bx => (m < bx.pickup ? 'onBoat' : m < bx.release ? 'inHands' : 'onDock'));
  }

  // ---------- media selection (PC 16:9 / phone portrait composition share one timeline) ----------
  const MV = '?v=4';   // media cache-buster (v4 2026-09-28: in-place idle loop, Korean workers, printed box logo)
  function pickMedia() {
    const key = phone.matches ? 'm' : 'pc';
    if (key === mediaKey) return;
    mediaKey = key;
    root.dataset.media = key;
    const prevP = p;
    video.src = T.media[key].video + MV;
    if (idle) { idle.dataset.src = (T.media[key].idle || `orca/media/idle-${key}.mp4`) + MV; idle.poster = T.media[key].poster + MV; if (pageLoaded) armIdle(); }
    video.poster = T.media[key].poster + MV;
    finalImg.src = T.media[key].final + MV;
    video.addEventListener('loadedmetadata', () => { shown = mediaTimeAt(prevP); try { video.currentTime = shown; } catch (e) {} }, { once: true });  // same p, this platform's media time
  }

  // ---------- presented-frame tracking (§6: currentTime assignment ≠ displayed frame) ----------
  let presented = -1;                         // media time of the last frame actually composited
  const rvfc = 'requestVideoFrameCallback' in HTMLVideoElement.prototype;
  function watchFrames() {
    if (!rvfc) return;
    const cb = (now, meta) => { presented = meta.mediaTime; video.requestVideoFrameCallback(cb); };
    video.requestVideoFrameCallback(cb);
  }
  video.addEventListener('seeked', () => { if (!rvfc) requestAnimationFrame(() => { presented = video.currentTime; }); });

  // ---------- scroll → p ----------
  let p = 0, shown = 0, raf = 0, degraded = false, finalShown = false;
  function readP() {
    const r = root.getBoundingClientRect();
    const range = root.offsetHeight - stage.offsetHeight;
    return range > 0 ? clamp(-r.top / range, 0, 1) : 0;
  }
  function frame() {
    raf = 0;
    p = readP();
    const target = mediaTimeAt(p);
    // ease toward the target so slow scrolls glide, fast flicks still land (distance-proportional)
    shown += (target - shown) * (Math.abs(target - shown) > 3 ? 0.5 : 0.18);
    if (Math.abs(target - shown) < 1 / 48) shown = target;
    if (!degraded && video.readyState >= 1 && Math.abs(video.currentTime - shown) > 1 / 60 && !video.seeking) {
      try { video.currentTime = shown; } catch (e) {}
    }
    render(target);
    if (Math.abs(target - shown) > 1 / 48) schedule();
  }
  const schedule = () => { if (!raf) raf = requestAnimationFrame(frame); };

  // ---------- state + DOM ----------
  let lastState = '';
  function render(target) {
    const b = bandAt(p);
    const bx = M().boxes; const m = degraded ? bx[bx.length - 1].release + 0.01 : shown;
    const boxes = boxesAt(m);
    const onDock = boxes.filter(s => s === 'onDock').length;
    const remaining = boxes.filter(s => s === 'onBoat').length;
    const lastReleased = boxes[boxes.length - 1] === 'onDock';
    // final branded frame: shown the instant the timeline is at/after DELIVERED (fast flick safe), and the
    // flag flips only after the image is decoded and a frame has been painted with it visible.
    const wantFinal = degraded || p >= T.deliveredP;
    if (wantFinal !== finalShown) {
      finalShown = wantFinal;
      root.classList.toggle('is-final', wantFinal);
      if (wantFinal) {
        const mark = () => requestAnimationFrame(() => requestAnimationFrame(() => { if (finalShown) root.dataset.finalPresented = 'true'; }));
        (finalImg.decode ? finalImg.decode() : Promise.resolve()).then(mark, mark);
      } else root.dataset.finalPresented = 'false';
    }
    root.style.setProperty('--oh-p', p.toFixed(4));
    const intro = clamp(1 - p / T.introP, 0, 1);
    root.style.setProperty('--oh-intro', intro.toFixed(3));
    idleUpdate(intro);
    root.dataset.state = b.state;
    root.dataset.delivered = onDock;
    root.dataset.remaining = remaining;
    root.dataset.lastReleased = lastReleased;
    const complete = onDock === 6 && remaining === 0 && lastReleased && root.dataset.finalPresented === 'true';
    root.dataset.handoff = degraded ? 'degraded' : complete ? 'normal' : 'pending';
    root.dataset.boxes = boxes.map(s => s[2]).join('');   // B/H/D… compact state for checks (onBoat→B, inHands→H, onDock→D)
    if (b.state !== lastState && status) {
      lastState = b.state;
      status.textContent = T.labels[b.state] || '';
    }
  }

  // ---------- idle loop + depth (only while the hero sits at the top) ----------
  // the idle loop is fetched only after window load, so the brand and the first frame are not slowed down (§7 budget)
  let pageLoaded = document.readyState === 'complete';
  function armIdle() { if (idle && idle.dataset.src && idle.getAttribute('src') !== idle.dataset.src) { idle.src = idle.dataset.src; idleOn = null; schedule(); } }
  addEventListener('load', () => { pageLoaded = true; armIdle(); }, { once: true });
  let idleOn = null;
  function idleUpdate(intro) {
    if (!idle) return;
    const on = !degraded && visible && intro > 0.02 && !reduce.matches;
    idle.style.opacity = on ? Math.min(1, intro * 1.6).toFixed(3) : '0';
    root.classList.toggle('is-idle', on && intro > 0.5);
    if (on !== idleOn) {
      idleOn = on;
      if (on) { const pr = idle.play(); if (pr && pr.catch) pr.catch(() => {}); } else idle.pause();
    }
  }
  // pointer parallax on the idle layer only (desktop): a small 3D drift gives depth to the static camera shot
  if (idle && matchMedia('(hover: hover) and (pointer: fine)').matches && !reduce.matches) {
    stage.addEventListener('pointermove', e => {
      const r = stage.getBoundingClientRect();
      root.style.setProperty('--oh-px', ((e.clientX - r.left) / r.width - 0.5).toFixed(3));
      root.style.setProperty('--oh-py', ((e.clientY - r.top) / r.height - 0.5).toFixed(3));
    }, { passive: true });
  }

  // ---------- resize / rotation keep p ----------
  let keepP = null;
  function onResizeStart() { if (keepP === null) keepP = p; }
  function onResizeEnd() {
    pickMedia();
    if (keepP !== null) {
      const range = root.offsetHeight - stage.offsetHeight;
      const top = root.getBoundingClientRect().top + scrollY;
      scrollTo({ top: top + keepP * range, behavior: 'instant' });
      keepP = null;
    }
    schedule();
  }
  let rt = 0;
  addEventListener('resize', () => { onResizeStart(); clearTimeout(rt); rt = setTimeout(onResizeEnd, 180); });

  // ---------- degraded path ----------
  function degrade(reason) {
    if (degraded) return;
    degraded = true;
    root.classList.add('is-degraded');
    root.dataset.degradedReason = reason;
    schedule();
  }
  video.addEventListener('error', () => degrade('video-error'));
  let stall = setTimeout(() => { if (video.readyState < 2) degrade('load-timeout'); }, T.loadTimeoutMs || 8000);
  video.addEventListener('loadeddata', () => clearTimeout(stall), { once: true });
  if (reduce.matches || navigator.connection?.saveData) degrade(reduce.matches ? 'reduced-motion' : 'save-data');

  // ---------- pause work when hidden ----------
  let visible = true;
  new IntersectionObserver(es => { visible = es[0].isIntersecting; if (visible) schedule(); else idleUpdate(0); }).observe(root);
  document.addEventListener('visibilitychange', () => { if (document.hidden && idle) idle.pause(); else schedule(); });
  // fast flick: decide the final branded frame inside the scroll event itself, so it is already on screen in the
  // same paint where the next section starts to appear (the rAF-driven render may run one frame later).
  addEventListener('scroll', () => {
    if (!degraded && !finalShown && readP() >= T.deliveredP) { p = readP(); render(mediaTimeAt(p)); }
    if (visible) schedule();
  }, { passive: true });
  phone.addEventListener('change', onResizeEnd);

  // first paint needs only metadata + poster (§7 first-bundle budget); the rest streams in once the page is idle
  addEventListener('load', () => setTimeout(() => { if (!degraded) video.preload = 'auto'; }, 1500), { once: true });
  root.classList.add('is-live');
  pickMedia();
  watchFrames();
  schedule();
  window.OrcaHero = { get p() { return p; }, get presented() { return presented; }, mediaTimeAt, boxesAt, bandAt, degrade };
})();
